ORNL/HydraGNN

example.py
hydragnn/run_prediction.py
hydragnn/run_training.py
hydragnn/unit_tests/test_graphs.py

@jychoi-hpc pointed out that multiple processes writing to the `tmp.json` file was likely causing the semi-regular MPI failures 
This adds overloads for `run_training` and `run_predict` that directly pass the config dictionary (modified during the test instead)
Also cleans up the interface for `run_predict`: config should be a required input and `chosen_model` was unused

Remove temporary unit test JSON

---

examples/configuration.json
hydragnn/preprocess/serialized_dataset_loader.py
tests/inputs/ci.json
tests/inputs/ci_multihead.json

Related to GraphRadius implemented in https://github.com/ORNL/HydraGNN/pull/30
Two changes:
1. set `loop` to be `False` in `RadiusGraph` to disable self-loops
2. Set `max_neighbours` in input files to be a large number to disable its constraint on maximum number of neighbors. After this change, the number of neighbors is purely determined by `radius`.

Improve neighbor computing

---

hydragnn/models/Base.py
hydragnn/models/PNAStack.py
hydragnn/models/create.py
hydragnn/preprocess/serialized_dataset_loader.py
tests/test_graphs.py

(From GCNN:)
With @pzhanggit 's help I have found:
- Only PNA and CGConv support
- GIN has an additional version GINE for edges
~~PNA currently breaks because we don't define the `edge_encoder`~~
~~GINE currently breaks because dimensions that don't agree (but I think actually do based on what I've checked)~~
Only implemented for PNA and CG (GINE does not have robust enough support to justify adding). New test only calls for these two models with edge lengths
Part of #2

Add edge lengths

---

hydragnn/models/create.py
hydragnn/preprocess/serialized_dataset_loader.py
hydragnn/train/train_validate_test.py
hydragnn/utils/__init__.py
hydragnn/utils/distributed.py
hydragnn/utils/time_utils.py

NEEDS TO BE TESTED ON THE DEVICE. But I'm pretty sure it works. I don't think this affects performance, just cleans up the code
- Move data to the device on loading, rather than every step. 
- Splits device name and device functions since we usually only want one or the other

Move data to the device once

---

hydragnn/postprocess/visualizer.py

Also makes scatter plot empty markers

added dashed red diagonal on scatterplot

---

.pre-commit-config.yaml
CONTRIBUTING.md
requirements-dev.txt

Fixes #75.
Based on the feedback provided by @streeve I've added `black` among some other miscellaneous checks to the `.pre-commit-config.yaml`. I've also added `pre-commit` to the `requirements-dev.txt` file in order to aid new contributors.
I have not added `pytest` as of right now based on the feedback provided but more than happy to take that up again. 
I'd also recommend adding instructions on how to install pre-commit hooks to the [**`CONTRIBUTING.md`**](https://github.com/ORNL/HydraGNN/blob/main/CONTRIBUTING.md) file.

Add `precommit`

---

hydragnn/preprocess/raw_dataset_loader.py
hydragnn/preprocess/utils.py
hydragnn/train/train_validate_test.py

This simplifies creating the histogram of nodes per graph, by using built-in `num_nodes` instead. Blocks #35

Remove num_nodes_list

---

hydragnn/train/train_validate_test.py
hydragnn/utils/profile.py

This fix blocks #35 and, only for older versions of pytorch, requires that we check for cuda before enabling cuda profiling

Check Cuda enabled for profiler

---

examples/ising_model/create_configurations.py

Makes the spin value randomization and non-linear spin function optional. With this update running the function with defaults results in the original Ising model

Make Ising example configurable

---

.github/workflows/CI.yml
tests/deterministic_graph_data.py
tests/inputs/ci.json
tests/inputs/ci_multihead.json
tests/test_graphs.py

This PR does 2 main things:
- Updates unit test to set node features to "type" (integers) and node outputs to KNN aggregated features (previously only the linear values were not updated)
- Sets separate thresholds for CG with and without edge lengths (intended to be done when added...)
~~Adds pytest step to remove all datasets (attempting to make sure we no longer have consistent failures on a given PR due to a particularly difficult to predict datset)~~
Will revisit this later. I don't know how to avoid random hangs
The rest is small cleanup ("clusters" is now "types", etc.)

Fixup tests

---

hydragnn/preprocess/load_data.py
hydragnn/preprocess/serialized_dataset_loader.py

Simplifies, for example, #94 PBC boolean user input (which should reasonably be in "Dataset") and #102 for rotational invariance (which should also reasonably be in "Dataset")

Pass full config when loading serialized data

---

hydragnn/utils/distributed.py

This is a quick fix for the error on CADES with Gloo. On CADES, we got a node name (not an IP address). I put `socket.gethostbyname` to translate node name into an IP address.

Quick fix for the error with find_ifname on CADES

---

examples/md17/md17.py
hydragnn/preprocess/__init__.py
hydragnn/preprocess/serialized_dataset_loader.py
hydragnn/preprocess/utils.py
tests/inputs/ci.json
tests/inputs/ci_multihead.json
tests/inputs/ci_rotational_invariance.json
tests/test_rotational_invariance.py

I am using the PyTorch Geometric transformation called `NormalizeRotation` 
https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/transforms/normalize_rotation.html#NormalizeRotation
This transformation computes the eigenvectors if the point could, and transforms data.pos by applying a rotation with respect to the eigenvectors. 
This transformation ensures that data.pos is rotational invariant. Any rotation applied to the graph affects the eigenvectors of the point cloud, but **the relative coordinates of data.pos with respect to the eigenvectors DO NOT CHANGE**
Part of #2

rotational invariance added

---

hydragnn/train/train_validate_test.py

Total number of samples (n_tot) in the dataset was used in calculating losses. This was fine in single rank runs.
But when multiple ranks were involved in DDP, the loss calculated would be less that the actual loss, since actual samples were split to each rank and the number of samples on each rank should be smaller (n_tot/n_ranks), but still the total number (n_tot) were used. 
This (probably) partially explains the large loss difference in multiple GPUs vs single GPU.

correct number of samples in loss calculation

---

requirements.txt

Click 8.1.0 conflicts with black
For now, to avoid clashes between version of packages, I force the click version to be click==8.0.0 in the `requirements.txt` file
CI tests are failing for accuracy, but this is unrelated to the issue addressed in the PR.

click version frozen to 8.0.0

---

examples/csce/train_gap.py
examples/ising_model/train_ising.py
examples/lsms/lsms.py
examples/ogb/train_gap.py
examples/qm9/qm9.py

In the examples folder, the variable `dirpwd` was set up with a relative path. 
`dirpwd = os.path.dirname(__file__)`
Everything worked fine on my laptop, OLCF Summit, and NERSC Perlmutter. However, I noticed that the serialized_dataset directory was alway created in the wrong place when the code was running on a docker on the DGX machine. The reason was that dirpwd was empty when the code was running on the docker. 
I googled and found this discussion:
https://stackoverflow.com/questions/7783308/os-path-dirname-file-returns-empty
Replacing the line above with 
`dirpwd = os.path.dirname(os.path.abspath(__file__))`
fixed the problem

absolute path added to dirpwd

---

hydragnn/train/train_validate_test.py

Currently, when there are multiple outputs/heads and all of them are graph-level properties, only the first property is read repeatedly due to indexing bug.

fix head indexing bug 

---

.github/workflows/CI.yml

version of Ubuntu frozen to 20.04 to avoid errors on newer version of libffi that changed from 7 to 8 on Ubuntu-22.04

version of Ubuntu frozen to 20.04 

---

README.md
hydragnn/models/SCFStack.py
hydragnn/models/create.py
hydragnn/utils/config_utils.py
tests/inputs/ci.json
tests/inputs/ci_multihead.json
tests/test_graphs.py

This pull request introduces the [SchNet](https://arxiv.org/abs/1706.08566) model to HydraGNN. SchNet is a powerful deep learning model that can accurately predict molecular properties from 3D molecular structures. 
Using the configuration `"model_type": "SchNet"` will initialize a convolutional stack `SCFStack`. Notice that PyG only offers [SchNet](https://pytorch-geometric.readthedocs.io/en/latest/_modules/torch_geometric/nn/models/schnet.html#SchNet) as a `nn.model` and not as a `nn.conv`. The `SCFStack` is a generalization of `SchNet` designed for HydraGNN.
The objective of this generalization is to provide full support for the convolutional layers of SchNet in the latent space. Functionally this means removing the embedding, decoding and layer stacking aspects of the `SchNet` and …

Added SchNet model as SCFStack

---

.pre-commit-config.yaml

This PR aims to resolve the first issue described in PR https://github.com/ORNL/HydraGNN/pull/178#issuecomment-1588027702 by pinning the `click` version in the setup of `pre-commit`.
I tested manually installing `black==21.5b1` and `click==8.0.0` as illustrated below, but encountered the same compatibility issue.
These compatibility issues are resolved using the `additional_dependencies` argument. *Notice:* I used `click==8.0.0` consistent with the version in https://github.com/ORNL/HydraGNN/blob/main/requirements.txt

Black + Click Version Controlling

---

hydragnn/preprocess/utils.py

All the data loaders use the `pin_memory=True`, which can work only if the data is stored on CPUs. 
If the entire data were stored on the GPU, `pin_memory=True` would make the code crash
Since all our data is stored on CPU, the `max_de`g and `deg ` variables are also stored on the CPU. Therefore, the NCCL gathering operations crash because they require the variables to be on the device. 
This PR fixed this problem.

gather_deg_dist needs to map 'deg' variable to GPUs before calling NCCL gathering operations

---

examples/md17/md17.py
examples/qm9/qm9.py
tests/test_model_loadpred.py

Keep examples on cpu in the pre_transform, so that they properly interact with memory pinning when being migrated to the gpu.

Init examples on cpu for memory pinning

---

hydragnn/train/train_validate_test.py
hydragnn/utils/model.py
tests/inputs/ci.json
tests/inputs/ci_multihead.json
tests/inputs/ci_vectoroutput.json

Basic checkpointing for training based on the synchronized `validation_loss` performance metric.
Can be turned on by adding
```
"Training" : {
"Checkpoint" : true,
}
```
with additional `checkpoint_freq` argument for the frequency of checkpointing (`default=10`)
```
"Training" : {
"Checkpoint" : true,
"checkpoint_freq" : 10,
}
```

Checkpoint Training Model

---

examples/ising_model/train_ising.py
hydragnn/utils/adiosdataset.py

Adios recently added new BP5 format. But, it is not compatible with what we are using in HydraGNN. 
We will use BP4 until we figure out the correct way to use BP5.
Another fix is about `sys.setrecursionlimit(1000000)`. It was needed when I create a large ising dataset.

Use Adios BP4

---

hydragnn/utils/abstractrawdataset.py

This PR addresses two issues:
- `self.__normalize_dataset()` is safeguarded by a boolean variable and used only when the user specifies it in the .JSON file
- fixes a bug that was hidden inside the `AbstractRawDataset` .
`update_predicted_values` and `update_atom_features` are already included in the SimplePickleDataset class. Therefore, there is no need to used them now inside `AbstractRawDataset`

abstractrawdataset updated

---

examples/qm7x/inference.py
examples/qm7x/qm7x.json
examples/qm7x/qm7x_single_tasking.json
examples/qm7x/train.py

@frobnitzem 
among all the energies that can be retrieved from the QM7x dataset, may you help me identify the one that corresponds to the energy returned by OC2020 and OC2022?

Qm7x dataset

---

hydragnn/models/Base.py
hydragnn/models/DIMEStack.py
requirements-pyg.txt
tests/inputs/ci_conv_head.json
tests/test_graphs.py

The capability to use a full stack of convolutional layers when only nodal predictions are needed was never tested in the code. 
This PR:
- updated pre-existing code to maintain support of `type="conv"` as a choice for nodal heads of HydraGNN
- has if-then-else conditions to make sure that `get_conv` is called with the proper number of arguments. All models except SCFStack take two input arguments. SCFStack takes also` last_layer`, which is a Boolean variable.

Graph heads ci tests

---

examples/multidataset/open_catalyst_energy.json
examples/multidataset/train.py
examples/open_catalyst_2020/train.py
hydragnn/utils/adiosdataset.py
hydragnn/utils/config_utils.py
hydragnn/utils/distdataset.py
hydragnn/utils/pickledataset.py

Two update:
* using multiple datasets for GB24
* addiiotn HYDRAGNN_USE_VARIABLE_GRAPH_SIZE env to skip the check if graph size is variable or not at starting.

Add multi dataset option for GB24

---

examples/qm9_hpo/dh_utils.py
examples/qm9_hpo/job-frontier.sh
examples/qm9_hpo/qm9.json
examples/qm9_hpo/qm9.py
examples/qm9_hpo/qm9_deephyper.py
examples/qm9_hpo/qm9_deephyper_multi.py
examples/qm9_hpo/qm9_optuna.py
examples/qm9_hpo/test_deephyper.py
hydragnn/utils/config_utils.py
hydragnn/utils/distributed.py

This PR introduces three main examples for hyperparameter optimization (HPO) using the QM9 dataset:
1. `qm9_optuna.py`: HPO example using `optuna`
2. `qm9_deephyper.py`: HPO example running in sequential using `deephyper`
3. `qm9_deephyper_multi.py`: HPO example running in parallel using `deephyper`

Testing hpo packages

---

examples/multidataset/train.py

Remove multi_process_list option in multidataset. It calculates number of processes per dataset based on the number of molecules in the files.

Remove multi_process_list option in multidataset

---

hydragnn/train/train_validate_test.py

I found my error on calculating nbatch, which caused the following error with DDStore:
```
terminate called after throwing an instance of 'std::logic_error'
what():  Fence already activated
```
This fixes the issue.

Fix for nbatch error

---

hydragnn/utils/model.py

`get_summary_writer()` in the current main branch has no return value so the tensorboard log file will never be written:
Current implementation in [hydragnn/utils/model.py](https://github.com/ORNL/HydraGNN/blob/5c4dcf4ef10cdc3ec97c1ec6e97ba922cc177fd6/hydragnn/utils/model.py#L74):
```python
def get_summary_writer(name, path="./logs/"):
_, world_rank = get_comm_size_and_rank()
if world_rank == 0:
path_name = os.path.join(path, name)
writer = SummaryWriter(path_name)
```
Example use case in [examples/ogb/train_gap.py](https://github.com/ORNL/HydraGNN/blob/5c4dcf4ef10cdc3ec97c1ec6e97ba922cc177fd6/examples/ogb/train_gap.py#L305):
```python
writer = hydragnn.utils.get_summary_writer(log_name)
```

Fix: no return value of get_summary_writer

---

setup.py

pickle5 is replaced with pickle for python > 3.7, thus pickle5 requirement is not needed.

Removed pickle5 requirement from setup.py

---

hydragnn/train/train_validate_test.py

A quick fix for
```
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
I found my previous commit has a problem. I missed host-to-device copying. This will be a fix.

Fix for runtime error for missing host-to-device copy

---

hydragnn/models/Base.py
hydragnn/models/create.py
hydragnn/utils/config_utils.py

[Checkpointing](https://pytorch.org/docs/stable/checkpoint.html) is a widely used technique (i.e. in [deepspeed](https://github.com/microsoft/DeepSpeed/blob/f4cb866c2eba60a72d79c3741d12d098fe4e45b8/deepspeed/runtime/activation_checkpointing/checkpointing.py#L725)) to reduce peak GPU memory consumption. It achieves this by recomputing intermediate activations during the backward pass instead of storing them from the forward pass.
This enhancement leverages PyTorch's official checkpoint implementation and applies it at a per convolution layer granuality.
Key features include:
+ Model agnosticism: It can be used with any type of message-passing layers.
+ Significant memory reduction: An 18-layer, 512-dimension PNA network (with batch_size=128) shows a peak memory usage reduction of …

Enhancement: model-agnostic layer-wise checkpointing

---

hydragnn/utils/adiosdataset.py

This adds a check to see if ADIOS is installed. It will fail with an ImportError if ADIOS is not found. We don't need to add any more error handling here.
Without this line, we get 
```
NameError: name 'ad2' is not defined
```
which is not intuitive.

Cleaner way to fail if ADIOS is not installed. #205

---

examples/ogb/train_gap.py
hydragnn/utils/distributed.py
job-frontier-ogb-deepspeed.sh
run_deepspeed_template.sh

As noted by @jychoi-hpc in the [previous pull request](https://github.com/ORNL/HydraGNN/pull/264#issuecomment-2237505680), the DeepSpeed backend fails to initialize when a rank has only one visible GPU (e.g., when launched with --`gpus-per-task=1`).
The root cause is that DeepSpeed defaults to determining GPU ordinals based on the `LOCAL_RANK` environment variable if no `device_rank` is passed, but with one visible GPU per rank, only device ordinal 0 is valid, which makes all ranks except local_rank 0 fails. 
Although this default mapping works when granting visibility of all GPUs to all ranks, it may not be optimal considering the [heterogeneous connectivity](https://docs.olcf.ornl.gov/systems/frontier_user_guide.html#frontier-compute-nodes) between CPU caches and GPUs on Frontier. For …

Enhancement: Deepspeed Launch Template & Now Compatible with GPU Binding

---

hydragnn/train/train_validate_test.py

This is a quick fix for adding CheckRemainingTime option. 
We need an option to enable/disable remaining time checking. In HPO running, we need to disable this function. In this update, we are disabling remaining time checking by default.

Quick fix for adding CheckRemainingTime option

---

examples/LennardJones/LJ.json
examples/LennardJones/LJ_data.py
examples/LennardJones/LennardJones.py
tests/test_forces_equivariant.py

This conducts force prediction tests. It directly pulls from the Lennard Jones example, rather than creating its own data independently as done in test_graphs.py. The model stacks that work with this are SchNet, EGNN, DimeNet, and PNAPlus.

Forces test

---

hydragnn/utils/smiles_utils.py
utils/import_csv.py

This pr adds a couple of lines to `hydragnn/utils/smiles_utils.py` and `utils/import_csv.py` to add molecular positions to the csv file. Here is how the data look using `bpls -a data.bp`. 
```
float    testset/pos                          {6741, 3}
int64_t  testset/pos/variable_count           {147}
int64_t  testset/pos/variable_dim             attr
int64_t  testset/pos/variable_offset          {147}
float    testset/x                            {6741, 6}
int64_t  testset/x/variable_count             {147}
int64_t  testset/x/variable_dim               attr
int64_t  testset/x/variable_offset            {147}
double   testset/y                            {294}
```

added positions for csv-to-adios pipeline

---

examples/alexandria/train.py
examples/ani1_x/train.py
examples/csce/train_gap.py
examples/eam/eam.py
examples/lsms/lsms.py
examples/multidataset/train.py
examples/multidataset_hpo/gfm.py
examples/open_catalyst_2020/train.py
examples/open_catalyst_2022/train.py
examples/qm7x/train.py

@AdithyaRaman 
Would you mind quickly reviewing this PR so that I can quickly merge it and fix the imports of ADIOS2 in the examples?

fixed adios2 dataset class import in examples

---

hydragnn/models/DIMEStack.py
hydragnn/models/create.py
hydragnn/utils/input_config_parsing/config_utils.py

This adds edge feature functionality to DimeNet.
When pairwise interaction messages are created through `f(xi,xj,rbf)`, I simply modify to concatenate edge features if desired, resulting in `f(xi,xj,rbf,edge_attr)`. 
The main changes were (1) The concatenation in the embedding block and  (2) Any conditional logic for optional edge_features.

DimeNet Edge Features Functionality

---

hydragnn/models/Base.py
hydragnn/models/CGCNNStack.py
hydragnn/models/DIMEStack.py
hydragnn/models/EGCLStack.py
hydragnn/models/GATStack.py
hydragnn/models/GINStack.py
hydragnn/models/MACEStack.py
hydragnn/models/MFCStack.py
hydragnn/models/PAINNStack.py
hydragnn/models/PNAEqStack.py
hydragnn/models/PNAPlusStack.py
hydragnn/models/PNAStack.py
hydragnn/models/SAGEStack.py
hydragnn/models/SCFStack.py
hydragnn/models/create.py

PR aimed at improving signatures and variable names to enhance model development.
- Signature change: `Base.__init__(input_args, conv_args, ...)` requires arguments to be specified in the input to the base class. This enables better wrapper development by instantiating `self.input_args, self.conv_args` among all classes inheriting from `Base`. [1](https://github.com/ORNL/HydraGNN/compare/main...JustinBakerMath:HydraGNN:main?expand=1#diff-70520dd20f8abb34415c44a777926e4ab8f6239be3e6ba9ac7fa3036d2e2baf5R30-R31) 
- Note: this will automatically handle `edge_attr` adding to the arguments if `use_edge_attr` is true [2](https://github.com/ORNL/HydraGNN/compare/main...JustinBakerMath:HydraGNN:main?expand=1#diff-70520dd20f8abb34415c44a777926e4ab8f6239be3e6ba9ac7fa3036d2e2baf5R111-R114).
- …

Light refactor to improve development

---

hydragnn/models/Base.py
hydragnn/models/MACEStack.py
hydragnn/utils/model/irreps_tools.py
hydragnn/utils/model/mace_utils/modules/blocks.py

Reworking of MACE for cleanliness, robustness to hyperparameter configurations, and numerical stability in decoders.
Main Changes:
(1) Many changes to cleanliness and comments, moving some blocks to the utils.
(2) Handle configurations with only one convolutional layer where both first_layer and last_layer are true
(3) Do not append multiple layers in the decoder block when doing a purely linear decoding. This is because multiple linear layers stacked on top of each other without activations can be cause more erratic training / numerical instability.

Reformatting MACE

---

examples/omat24/download_dataset.py
examples/omat24/example_requirements.txt
examples/omat24/omat24_energy.json
examples/omat24/omat24_forces.json
examples/omat24/train.py

@ArCho48 @RylieWeaver 
I would like for you to take a look at how the code is structured, so that you can start getting acquainted with how we import new datasets in HydraGNN.

omat24 example

---

examples/LennardJones/LJ.json
examples/LennardJones/LJ_data.py
examples/LennardJones/LJ_inference_plots.py
examples/alexandria/train.py
examples/mptrj/train.py
examples/omat24/train.py
examples/open_catalyst_2020/train.py
examples/open_catalyst_2020/utils/atoms_to_graphs.py
examples/open_catalyst_2022/train.py
hydragnn/preprocess/cfg_raw_dataset_loader.py
hydragnn/preprocess/graph_samples_checks_and_updates.py
tests/test_periodic_boundary_conditions.py

This PR aims to accomplish four main things:
(1) Align the OC examples with their datasets in the literature, which always have PBC
(2) Unify the naming of `cell` in the examples and all other parts of HydraGNN. Including `cell` is required by PBC
(3) Improved simplicity of the LJ example
-  Using tools for `edge_vec` and `forces`, rather than manual
(4) Improved robustness of applying pbc
- Checking for dupe edges instead of a check on radius, since the radius check can falter for non-cubic PBC
- Adjusting the radius in OC examples so as to not create dupe edges

Align examples pbc

---

examples/multibranch/gfm_multibranch.json
examples/multibranch/gfm_multibranch_physics-informed.json
examples/multibranch/train.py
hydragnn/models/Base.py
hydragnn/utils/distributed/distributed.py
hydragnn/utils/input_config_parsing/config_utils.py
job-multibranch.sh

to support HydraGNN cases where users need dataset-specific heads for the same variable across multiple datasets.

Dev hierarchical multibranch output heads 

---

examples/multibranch/train.py
hydragnn/utils/input_config_parsing/config_utils.py
job-multibranch.sh

This is a draft for how we may fix the nodal MLP's output dimension when using compute_grad_energy. This way, the output dimension is dictated by the config's instead of the node feature dim. We are still setting up dummy data.y and data.y_loc variables, but not using them, but this fix may be minimally invasive.
NOTE: In detail: When using Hydra for physics-informed force prediction for the GFM, we have the following structure:

Fix Nodal Output Dim for Compute-Grad-Energy

---

hydragnn/models/SCFStack.py
hydragnn/preprocess/graph_samples_checks_and_updates.py

If `torch.cuda.is_available()`, use the radius graph as before. If not, then use a subclass of SchNet's radgraph that transfers tensors to CPU, executes the radgraph, and then puts the tensors back on the original device. 
The `torch.cuda.is_available()` check will be true for both CUDA and ROCm, so it still uses the GPU on Frontier as we'd want.

Make SchNet RadGraph divert to CPU on Hardwares that don't have PyG GPU Support

---

examples/qm7x/train.py
examples/transition1x/train.py

In train.py of qm7x and transition1x, the explicit ddstore call is moved inside the pickle block

Update pickle+ddstore in qm7x and transition1x

---

examples/LennardJones/LennardJones.py
examples/alexandria/train.py
examples/ani1_x/train.py
examples/csce/train_gap.py
examples/dftb_uv_spectrum/train_discrete_uv_spectrum.py
examples/dftb_uv_spectrum/train_smooth_uv_spectrum.py
examples/eam/eam.py
examples/ising_model/train_ising.py
examples/lsms/lsms.py
examples/md17/md17.py
examples/mptrj/train.py
examples/multibranch/train.py
examples/multibranch_hpo/train.py
examples/multidataset/train.py
examples/multidataset_deepspeed/train.py
examples/multidataset_hpo/gfm.py
examples/ogb/train_gap.py
examples/open_catalyst_2020/train.py
examples/open_catalyst_2022/train.py
examples/open_materials_2024/train.py
examples/open_molecules_2025/train.py
examples/qm7x/train.py
examples/qm9/qm9.py
examples/qm9_hpo/qm9.py
examples/qm9_hpo/qm9_deephyper.py
examples/qm9_hpo/qm9_optuna.py
examples/transition1x/train.py
examples/zinc/zinc.py
hydragnn/run_training.py
tests/test_datasetclass_inheritance.py

This PR adds a quick fix to ensure that the TensorBoard writer is properly closed in all examples.
We opened the writer using:
```
writer = hydragnn.utils.get_summary_writer(log_name)
```
but many examples did not explicitly close it. This sometimes resulted in TensorBoard logs not being written out cleanly.
To address this, I added the following snippet at the end of all examples
```
if writer is not None:
writer.close()
```
This will the logs are flushed and closed properly.

Adding tensorboard writer close

---

hydragnn/utils/profiling_and_tracing/tracer.py

Quick fix to remove excessive messages like: 
```
GPTL error:GPTLquery: requested timer get does not have a name hash
```

Quick fix to remove excessive GPTL message

---

examples/multidataset_deepspeed/train.py
hydragnn/run_prediction.py
hydragnn/run_training.py
hydragnn/train/train_validate_test.py
hydragnn/utils/distributed/__init__.py
hydragnn/utils/distributed/distributed.py
hydragnn/utils/optimizer/optimizer.py
hydragnn/utils/profiling_and_tracing/tracer.py

This update adds support for bf16 in PyTorch/PyG with DeepSpeed integration. 
Main updates:
* Incorporated Pei’s initial bf16 implementation.
* Enabled bf16 support in DeepSpeed.
* Updated `distributed_model_wrapper` to toggle bf16 mode with or without DeepSpeed.
* Main example to demonstrate those changes is `examples/multidataset_deepspeed/train.py`

Enable bf16 support in PyTorch/PyG and DeepSpeed
