ORNL/HydraGNN

.gitignore, requirements-dev.txt, setup.py
Add `setup.py`. Add installation files to `.gitignore`
=> setup file added

hydragnn/preprocess/__init__.py, hydragnn/preprocess/dataset_descriptors.py, hydragnn/preprocess/load_data.py, hydragnn/run_prediction.py, hydragnn/run_training.py
1. fixed a bug when loading datasets separately for training/test/validate
2. remove the need that dataset has to be one of the prescribed in dataset_descriptors.py
3. fix a bug related to  https://github.com/ORNL/HydraGNN/pull/22
=> Improve dataset loading

hydragnn/preprocess/load_data.py, tests/inputs/ci.json, tests/inputs/ci_multihead.json, tests/test_graphs.py
Closes https://github.com/ORNL/HydraGNN/issues/39
~~[Note: rebased on #38, should review/merge #38 first]~~
=>  Add loading pkl option

hydragnn/run_prediction.py
the difference between true and True as string was causing the denormalization to never happen
=> output_denormalize treated as Boolean variable

hydragnn/models/Base.py, hydragnn/models/CGCNNStack.py, hydragnn/models/GATStack.py, hydragnn/models/GINStack.py, hydragnn/models/MFCStack.py, hydragnn/models/PNAStack.py, hydragnn/models/__init__.py, hydragnn/models/create.py, hydragnn/run_prediction.py, hydragnn/run_training.py, hydragnn/utils/model.py
Similar to #48, updating model creation:
- adds version without config input
- separates config input from individual models
- makes inputs only needed for PNA optional
=> Simplify model creation

hydragnn/models/Base.py, hydragnn/postprocess/visualizer.py, hydragnn/run_prediction.py, hydragnn/train/train_validate_test.py, tests/test_graphs.py
=> Clean up error naming and list issues 

.github/workflows/CI.yml, hydragnn/postprocess/postprocess.py
Used this assertion warning introduced in #45 to test and make sure that we can treat warnings as errors in the CI. This should now help keep the code warning free
=> Fix assertion warning

hydragnn/utils/model.py
=> mapping of PNA degree tensor to GPU

examples/lsms/lsms.json, tests/inputs/ci.json, tests/inputs/ci_multihead.json
=> Set nonzero verbosity

examples/lsms/lsms.json, hydragnn/preprocess/__init__.py, hydragnn/preprocess/load_data.py, hydragnn/preprocess/raw_dataset_loader.py, hydragnn/run_prediction.py, hydragnn/run_training.py, hydragnn/utils/config_utils.py, tests/inputs/ci.json, tests/inputs/ci_multihead.json, tests/test_graphs.py
=> save train/val/test pk files when raw total provided

hydragnn/postprocess/postprocess.py, hydragnn/run_prediction.py, hydragnn/utils/config_utils.py
=> Fixing bug in normalization

hydragnn/run_prediction.py, hydragnn/run_training.py, hydragnn/utils/__init__.py, hydragnn/utils/config_utils.py
Small fixup and simplification. Output name only needs config, not model
=> Simplify output name

hydragnn/run_training.py, hydragnn/train/train_validate_test.py, hydragnn/utils/profile.py
This is a PR for adding profiling routines based on PyTorch's Profiler.
=> Adding profiling function

hydragnn/models/PNAStack.py, hydragnn/models/create.py, hydragnn/run_prediction.py, hydragnn/run_training.py, hydragnn/utils/__init__.py, hydragnn/utils/config_utils.py, tests/test_graphs.py
=> Wrap up config updates in to utils

hydragnn/utils/distributed.py, requirements.txt
This is a quick fix causing a hang when using GLOO ddp (typically running on a local desktop).
This is based on this article: `https://pytorch.org/docs/stable/distributed.html#common-environment-variables`
=> update for GLOO ddp setup

.github/workflows/CI.yml, example.py, examples/lsms/lsms.py, examples/md17/md17.json, examples/md17/md17.py, examples/qm9/qm9.json, examples/qm9/qm9.py, hydragnn/preprocess/__init__.py, hydragnn/preprocess/serialized_dataset_loader.py, hydragnn/utils/__init__.py, tests/test_config.py, tests/test_examples.py
- QM9 molecular dataset
- MD17 molecular trajectory dataset
Part of #5 
Need to install to run: `python setup.py develop` or `python setup.py install`
OR add to the python path as in the CI
=> Add torch_geometric datasets

tests/test_graphs.py
Never the last time, but this seems to be the only current failure
=> Update test error threshold

examples/md17/md17.py, examples/qm9/qm9.py, hydragnn/preprocess/load_data.py, hydragnn/run_prediction.py, hydragnn/run_training.py, hydragnn/train/train_validate_test.py
Added the following for each epoch, otherwise the same sampling ordering will be used for every epoch, see https://github.com/pytorch/pytorch/blob/master/torch/utils/data/distributed.py.  
```
for sampler in sampler_list:
sampler.set_epoch(epoch)
```
=> fix a bug in data loading

examples/ising_model/ising_model.json, examples/lsms/lsms.json, examples/md17/md17.py, examples/qm9/qm9.py, hydragnn/run_training.py, hydragnn/train/train_validate_test.py, hydragnn/utils/__init__.py, hydragnn/utils/distributed.py, hydragnn/utils/print_utils.py
Add a python logging feature (`https://docs.python.org/3/library/logging.html`) to print messages to the screen as well as to a file (`run.log`).
Three functions are added:
* `logging_init`: setup logging
* `info`: print message prefixed with "[rank:INFO]"
* `log`: print message prefixed with "[rank:DEBUG]"
=> Logging feature

hydragnn/preprocess/__init__.py, hydragnn/preprocess/utils.py, hydragnn/utils/config_utils.py
The function `check_if_graph_size_constant` returns True if the graphs are variable. 
Given then meaning of the value return, the name of the function is quite confusing. 
Therefore, I renamed it with a name that better matches with the meaning of the variable returned.
=> check_if_graph_size_constant renamed to check_if_graph_size_variable

tests/test_enthalpy.py
=> Do not create plots during tests

hydragnn/preprocess/raw_dataset_loader.py
This will facilitate the conclusion of additional `__transform methods` to support multiple data formats
=> opening of raw data file moved into __transform method

tests/test_graphs.py
Pretty consistent failures in the cron jobs and recent PR
=> Increase CG threshold

hydragnn/models/SAGEStack.py, hydragnn/models/create.py, tests/test_graphs.py
This is one of the simplest convolutional layers.
The introduction of this additional convolutional layer is minimally invasive with respect to the existing version of the repository, and helps us move towards the goal of introducing hyper parameter optimization in the repo, where the choice of the convolutional layer (GIN, GAT, PNA, CGCNN, SAGE) will be an hyper parameter to optimize to maximize validation accuracy.
=> SAGEStack added

hydragnn/models/Base.py, hydragnn/models/create.py, hydragnn/utils/config_utils.py
Very similar to freezing layers from #111 
Note - this isn't checked in the CI
=> Add option to set large output bias for UQ

hydragnn/preprocess/serialized_dataset_loader.py, tests/inputs/ci_vectoroutput.json, tests/test_graphs.py
Fix indexing bug and update unit test
=> fix indexing bug

hydragnn/run_training.py, hydragnn/utils/model.py
This is an update for checkpointing and restarting. 
Now it saves both model and optimizer states and loads when restarting. It works in a distributed setting too.
=> Update on checkpointing

examples/md17/md17.json, examples/md17/md17.py, examples/qm9/qm9.json, examples/qm9/qm9.py, hydragnn/models/Base.py, hydragnn/models/GATStack.py, hydragnn/postprocess/visualizer.py, hydragnn/preprocess/load_data.py, hydragnn/run_prediction.py, hydragnn/run_training.py, hydragnn/train/train_validate_test.py, hydragnn/utils/config_utils.py, hydragnn/utils/distributed.py, hydragnn/utils/model.py, tests/test_graphs.py, tests/test_model_loadpred.py
Major features/changes:
1. Fixed a bug in DDP model. The DDP wrapped model was unwrapped (which is not supposed to be) before training. As a result, every process trains its own model with a subset of dataset and there is no synchronization between them. 
2. Fixed a bug about map_location in model loading
3. Added reduce/gather feature for loss log and results collection
4. Added SyncBatchNorm 
Checked that the gradients and model parameters on rank 0 and rank 1 are the same
=> DDP bug fix

hydragnn/models/Base.py
remove unnecessary clones; switch relu and linear
=> remove unnecessary clones 

examples/lsms/lsms.json, examples/lsms/lsms.py, hydragnn/train/train_validate_test.py, hydragnn/utils/config_utils.py
Update lsms  following the style in ising example
=> Lsms example

examples/csce/train_gap.py, examples/ising_model/train_ising.py, examples/ogb/train_gap.py, hydragnn/utils/adiosdataset.py, hydragnn/utils/pickledataset.py
This PR contains he followings:
* make adios2 import as optional 
* Fix for using `loader.dataset` in plotting
=> Update to make adios2 import as optional

hydragnn/preprocess/serialized_dataset_loader.py
Local descriptors added from the list of PyTorch-Geometric transformations provided in:
https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms
The transformations added are: 
- [Spherical](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.Spherical)
- [PointPairFeatures](https://pytorch-geometric.readthedocs.io/en/latest/modules/transforms.html#torch_geometric.transforms.PointPairFeatures)
=> local descriptors added

hydragnn/utils/__init__.py, hydragnn/utils/atomicdescriptors.py, requirements-dev.txt, tests/__init__.py, tests/test_atomicdescriptors.py
Add atomic descriptors from Mendeleev (https://mendeleev.readthedocs.io/en/stable/index.html)
=> Add atomic descriptors from Mendeleev

examples/md17/md17.py
Reverts ORNL/HydraGNN#159 because @jychoi-hpc  has a better solution.
=> Revert and improve "update filename in md17 since url broken"

examples/lsms/lsms.py, hydragnn/preprocess/raw_dataset_loader.py
Minor fix for the lsms example
=> Minor fix for lsms

hydragnn/models/Base.py
Separate the handling of convolutional arguments generated by the data object. The function `_conv_args `preserves the utility of `use_edge_attr`.
Furthermore, the inheritance of the convolutional stacks allows `data.pos` to be extracted as desired e.g. SchNet.
=> Separate handling of conv args

README.md, hydragnn/models/EGCLStack.py, hydragnn/models/create.py, hydragnn/utils/config_utils.py, tests/test_graphs.py
Preliminary [EGNN](https://arxiv.org/abs/2102.09844) model without `pos` updating.
Modified from https://github.com/vgsatorras/egnn.
Additional hyperparameters are left with default values and without explicit calls through the configuration.
=> EGNN Model

hydragnn/preprocess/__init__.py, hydragnn/preprocess/utils.py, hydragnn/utils/abstractrawdataset.py
The function `update_atom_features` is already available in the file `hydragnn\preprocess\utils.py`.
Therefore, there is no need to have a re-implementation as method inside the class `abstractrawdataset`.
The function `stratified_sampling` is a general functionality, and its use it not restricted to only datasets created with the class `abstractrawdataset`.
=> restructure pre-process data utils

README.md, setup.py
=> Fix for pypi upload

examples/qm9/qm9_custom20.py, examples/qm9/qm9_utils.py
These changes make the analysis step work with the torch 2.1.1+cu121 version I am using.
A try/except block over training allow loading an existing model rather than starting again from scratch.  It was useful for plotting outputs differently.
=> Log 2023 qm9 example update

hydragnn/utils/adiosdataset.py, hydragnn/utils/pickledataset.py
Just made minor fixes in dataset.
=> Minor fix for dataset

examples/open_catalyst_2020/open_catalyst_energy.json, examples/open_catalyst_2020/open_catalyst_forces.json, examples/open_catalyst_2020/utils/atoms_to_graphs.py, examples/open_catalyst_2022/open_catalyst_energy.json, examples/open_catalyst_2022/open_catalyst_forces.json, examples/open_catalyst_2022/train.py
This PR include the following:
1. removes unused import in Open Catalyst 2020 example
2. includes new example for Open Catalyst 2022. I tested the code on Frontier to create AIOS binary files and kick off the training, and it works.
=> Open catalyst 2022

requirements-pyg.txt
=> upgrade pyg 2.5.2

requirements-pyg.txt
import of "pyg-lib" corrected in the` requirements.txt`
=> pyg_lib corrected into pyg-lib

examples/multidataset/train.py, examples/multidataset_hpo/gfm.py, examples/multidataset_hpo/gfm_deephyper_multi.py
This is an update to merge multiple PNA deg for multi-datasets.
=> Merging multiple PNA deg for multi dataset

examples/multidataset_hpo/gfm.py, examples/multidataset_hpo/gfm_deephyper_multi.py, examples/multidataset_hpo/job-frontier.sh
* adjust hyper parameter max
* Job size for Frontier
* Add main() in `gfm.py` to capture any error
=> Update on HPO runs

examples/multidataset_hpo/gfm.py, examples/multidataset_hpo/gfm_deephyper_multi.py, examples/multidataset_hpo/job-frontier.sh
=> Update HPO based on multi

examples/multidataset/train.py, examples/multidataset_hpo/gfm.py, hydragnn/utils/adiosdataset.py
Adding "num_samples" option to use weak-scaling for multidataset.
=> Adding weak-scaling option for multidataset

examples/multidataset_hpo/gfm_deephyper_multi.py, examples/qm9_hpo/qm9_deephyper.py, examples/qm9_hpo/qm9_deephyper_multi.py
flipped sign in validation loss functions because DeepHyper maximize the objective function
=> flipped sign in validation loss functions return by HPO trials

examples/multidataset_hpo/gfm.py, examples/multidataset_hpo/gfm_deephyper_multi_perlmutter.py, examples/multidataset_hpo/job-perlmutter.sh, examples/open_catalyst_2020/train.py, hydragnn/train/train_validate_test.py, hydragnn/utils/deephyper.py
This include the update made for running HPO on Perlmutter.
=> Updating HPO for Perlmutter

examples/multidataset/train.py, hydragnn/train/train_validate_test.py, hydragnn/utils/adiosdataset.py, hydragnn/utils/distdataset.py, hydragnn/utils/distributed.py
This includes a few updates:
* Update on DDStore epoch begin/end routine 
* Adding check_remaining time routine within a job allocation on Frontier and Perlmutter
=> Minor updates on DDStore and remaining time checking

hydragnn/train/train_validate_test.py, hydragnn/utils/tracer.py
This update includes:
* Adding cudasync for timing to synchronize between cpu and gpu
* Add more timers (forward sync and backward sync to measure imbalance)
Ref: https://www.speechmatics.com/company/articles-and-news/timing-operations-in-pytorch
=> Add cudasync

hydragnn/utils/model.py, setup.py
Sigmoid activation function option is added to model.py
=> added sigmoid activation function

examples/qm7x/train.py
Check on value of L2-norm of force tensors added to filter out atomistic structures that are not feasible.
=> Qm7x check forces

examples/open_catalyst_2020/train.py
Functionalities to check on value of atomic forces added to example with Open Catalyst 2020 dataset
=> OC2020 check forces

hydragnn/train/train_validate_test.py
=> printing training, validation, and testing loss functions for each task 

hydragnn/utils/deephyper.py
Quick fix for running DeepHyper using a single node.
=> Update deephyper node list util

hydragnn/utils/distributed.py
Adding HYDRAGNN_MASTER_ADDR env to set custom DDP port.
=> Adding HYDRAGNN_MASTER_PORT

examples/ogb/train_gap.py, hydragnn/utils/adiosdataset.py
We have identified several issues with the original implementation in [examples/ogb/train_gap.py](https://github.com/ORNL/HydraGNN/blob/main/examples/ogb/train_gap.py) that require modifications:
1. **Incompatibility with the Current OGB PCQM4Mv2 Dataset**: The current version of the [OGB PCQM4Mv2](https://ogb.stanford.edu/docs/lsc/pcqm4mv2/) dataset includes atoms not listed in ogb_node_types and contains entries with empty labels. We skipped these incompatible entries in the preprocessing code.
2. **Failed Instantiation of `AdiosDataset`**: The code currently instantiates `AdiosDataset` with incompatible parameters. The `opt` dictionary should be unpacked before being passed as arguments.
3. **Broadcasting Over 2GB Data with MPI**: The `Adios_writer` class occasionally attempts to …
=> Bug Fix: Preprocessing and Training with the OGB PCQM4Mv2 Dataset

examples/multidataset/energy_linear_regression.py, examples/multidataset/gfm_multitasking.json
This is to add a script for energy linear regression.
=> Energy linear regression

hydragnn/models/create.py
Just two lines changed
Since it's unrelated to my other work, I opened a separate PR for organization.
=> Fix a Typo

examples/multidataset/dataset_histogram_plot.py
Adding a script to generate histogram plots for datasets
=> Script to plot dataset histogram

hydragnn/models/PAINNStack.py
Small fix here. Would cause an error with hanging gradients if only one convolutional layer.
=> Small fix PAINN Hanging Gradients

hydragnn/models/DIMEStack.py
Small PR to add a comment on how DimeNet is invariant. Let me know if it's better to add elsewhere.
=> Dime Invariant Comment

hydragnn/models/PAINNStack.py, hydragnn/models/create.py, hydragnn/utils/input_config_parsing/config_utils.py
This PR aims to add edge attributes into the PAINN message-passing stack
=> Add edge_attr into PAINN

.github/workflows/CI.yml, examples/multidataset_deepspeed/launch_helper.py, examples/multidataset_deepspeed/train.py
This PR performs two updates:
1. Updates caching for CI workflows from version v2 to version v4: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/
2. fixes on Chadian's script to fix the black formatting.
=> update caching from v2 to v4 for CI workflows and fix formatting of deepspeed example 

examples/multibranch/energy_linear_regression.py, examples/multibranch/train.py
normalization of chemical composition histogram removed from calculation of linear regression term
=> normalization of chemical composition histogram removed from calculation of linear regression term

hydragnn/utils/distributed/__init__.py, hydragnn/utils/distributed/distributed.py
Added functionalities in `hydragnn/utils/distributed` to run HydraNN on ALCF-Aurora
=> Distributed intel gpus

requirements-pyg.txt
Please confirm that indeed pyg-lib is useless
=> remove pyg-lib requirement

examples/ani1_x/download_andes.sh, examples/ani1_x/train.py, examples/mptrj/download_data_andes.sh, examples/transition1x/download_dataset.sh
Rectified spelling from self.max_neighbors to self.max_neighbours
=> Update ani1_x train.py

examples/qm9/qm9.py, hydragnn/utils/profiling_and_tracing/tracer.py
This is for enabling NVidia energy profiling. @AdithyaRaman did a great job. This is minor modification.
=> NVIDIA and AMD energy profile

hydragnn/utils/datasets/abstractbasedataset.py
Adding +3 datasets for multibranch
Assigning a default value for other examples which is not using mulitask
=> Adding extra datasets for multibranch

README.md, USER_MANUAL.md
I tested the Pro version of GitHub's copilot. 
I there the ORNL/HydraGNN GitHub hyperlink into it, and asked him to provide a comprehensive guide for users to help them get acquainted with the code. 
If you guys like this preliminary documentation, we can include it as a USER_MANUAL.md
=> Improved documentation

hydragnn/utils/input_config_parsing/config_utils.py
@RylieWeaver 
Was there a good reason why we did not add DimeNet to the list of models that allow equivariance, or was that just an overlooked?
=> added DimeNet model to list of models that allow equivariance

examples/open_catalyst_2020/download_dataset.py, examples/open_materials_2024/omat24.py, examples/open_molecules_2025/omol25.py, examples/qm7x/download_dataset.sh, hydragnn/utils/datasets/adiosdataset.py
Minor fixes made during the data pre-preprocessing last week
=> Minor fixes for pre-preocessing

hydragnn/train/train_validate_test.py, hydragnn/utils/distributed/distributed.py, hydragnn/utils/profiling_and_tracing/tracer.py
Quick fixes for using bf16 on Aurora.
=> Quick fixes for Aurora
